name: vulnerabilities

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '17 4 * * 1'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.98.1

jobs:
  advisories:
    name: advisories
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: knotrel-benchmarks
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: knotrel-benchmarks
          persist-credentials: false
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: knotrel/knotrel
          ref: main
          path: knotrel
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
        with:
          workspaces: knotrel-benchmarks -> target
      - run: cargo install cargo-deny --locked
      - run: cargo deny check advisories
